import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';

export async function POST(request) {
  try {
    const { prompt, pageNumber, storybookId, characters, charactersInScene, styleGuide } = await request.json();

    if (!prompt || pageNumber === undefined || !storybookId) {
      return NextResponse.json(
        { error: 'Missing required parameters: prompt, pageNumber, or storybookId' },
        { status: 400 }
      );
    }

    // Use DALL-E 3 for image generation
    const openaiApiKey = process.env.OPENAI_API_KEY;

    if (!openaiApiKey) {
      throw new Error('Missing OPENAI_API_KEY environment variable');
    }

    // Build enhanced prompt with character consistency
    let enhancedPrompt = '';

    // Add style guide first (most important for overall look)
    if (styleGuide) {
      enhancedPrompt += `${styleGuide}. `;
    }

    // Add character descriptions for characters in this scene
    if (characters && charactersInScene && charactersInScene.length > 0) {
      enhancedPrompt += 'Characters in scene: ';
      const sceneCharacters = characters.filter(char =>
        charactersInScene.includes(char.name)
      );

      sceneCharacters.forEach((char, index) => {
        // Use detailed appearance with no punctuation breaks (better for DALL-E consistency)
        enhancedPrompt += `${char.name} with ${char.appearance}`;
        if (index < sceneCharacters.length - 1) {
          enhancedPrompt += ', ';
        }
      });
      enhancedPrompt += '. ';
    }

    // Add the scene-specific prompt
    enhancedPrompt += prompt;

    // Add consistency reminder
    enhancedPrompt += '. Maintain exact same character appearance as described, consistent style throughout, portrait orientation.';

    console.log('Enhanced prompt for page', pageNumber, ':', enhancedPrompt);

    // Call OpenAI DALL-E 3 API
    const dalleResponse = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openaiApiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'dall-e-3',
        prompt: enhancedPrompt,
        n: 1,
        size: '1024x1792', // Closest to 3:4 aspect ratio (portrait)
        quality: 'hd', // Use HD quality for better consistency and details
        style: 'vivid', // Vivid for more dramatic, stylized images
        response_format: 'b64_json' // Get base64 encoded image
      })
    });

    if (!dalleResponse.ok) {
      const errorText = await dalleResponse.text();
      console.error('DALL-E 3 error:', errorText);
      throw new Error(`DALL-E 3 failed: ${dalleResponse.status} - ${errorText}`);
    }

    const dalleData = await dalleResponse.json();

    if (!dalleData.data || dalleData.data.length === 0) {
      throw new Error('No image generated by DALL-E 3');
    }

    // Get base64 image from response
    const imageBase64 = dalleData.data[0].b64_json;

    if (!imageBase64) {
      throw new Error('No image data in DALL-E 3 response');
    }

    // Convert base64 to buffer
    const imageBuffer = Buffer.from(imageBase64, 'base64');

    // Upload to Supabase Storage using admin client (bypasses RLS)
    const fileName = `${storybookId}/page-${pageNumber}.png`;
    const { data: uploadData, error: uploadError } = await supabaseAdmin.storage
      .from('storybook-images')
      .upload(fileName, imageBuffer, {
        contentType: 'image/png',
        upsert: true
      });

    if (uploadError) {
      console.error('Supabase upload error:', uploadError);
      throw new Error(`Failed to upload image: ${uploadError.message}`);
    }

    // Get public URL
    const { data: { publicUrl } } = supabaseAdmin.storage
      .from('storybook-images')
      .getPublicUrl(fileName);

    return NextResponse.json({
      success: true,
      imageUrl: publicUrl,
      pageNumber
    });

  } catch (error) {
    console.error('Error generating image:', error);
    return NextResponse.json(
      { error: 'Failed to generate image', details: error.message },
      { status: 500 }
    );
  }
}
